[project]
name = "scripty-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "panel>=1.5.5",
    "polars>=1.20.0",
    "pyscript>=0.3.3",
    "python-ags4>=1.0.0",
]
