[project]
name = "scripty-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrr>=1.0.5",
    "matplotlib>=3.10.0",
    "pyscript>=0.3.3",
]
